const appname = "eCommerce App";
const appversion = "Version 2.1.0";
const credits = "@Roaster";
const email = 'Email';
const emailHint = 'Roaster@gmail.com';
const password = 'Password';
const passwordHint = 'Roaster@123';
const forgetPass = 'Forget Password ?';
const login = 'Log In';
const logout = 'Log Out';
const sigup = 'Sign Up';
const createNewAccount = 'or, Create a new Account';
const loginWith = 'Log In with';
const name = 'Name';
const nameHint = 'Roaster';
const resetPass = 'Reset PassWord';
const retypePass = 'Retype your Password';
const privacyPolicy = 'Privacy Policy';
const termAndCond = 'Terms & Conditions';
const loggedIn = 'Logded In Successfully';
const logdedOut = 'Logged Out Successfully';

const home = 'Home',
    categories = 'Categories',
    cart = 'Cart',
    account = 'Account';

const searchAnything = 'Search Anything you like ...',
    todayDeal = 'Today\'s Deal',
    flashDeal = 'Flash Deal',
    topSeller = 'Top Seller\'s',
    brand = 'Brand',
    topcategory = 'Top Categories',
    womenDress = 'Women Dresses',
    girlsWatch = 'Girl\'s Watches',
    mobilePhone = 'Mobile Phone',
    boysGlasses = 'Mobile Phone',
    tShirts = 'TShirts',
    girlDress = 'Girls Dresses',
    featuredCategory = 'FeaturedCategories';

const womenClothing = 'Women Dress',
    menClothing = 'Men Clothing & Fashion',
    compAccess = 'Computer & Accessories',
    automobile = 'AutoMobile',
    kidToys = 'Kids & Toys',
    sports = 'Sports',
    jewelery = 'Jewelery',
    cellphone = 'Cellphone & Tab',
    furniture = 'Furniture';

const video = 'Video',
    reviews = 'Review\'s',
    sellerPolicy = 'Seller Policy',
    returnPolicy = 'Return Policy',
    supportPolicy = 'Support Policy',
    productyoualsolike = 'Product\'s you also like';

const wishlist = 'My WishList',
    orders = 'My Orders',
    messages = 'Messages',
    oldpass = 'Old Password',
    newpass = 'New Password';
